benchmarks/2017.json
benchmarks/benchmarks-schema.yaml
index.js
package.json
test/benchmarks/benchmarks-spec.js
test/util/format-benchmark-record-spec.js
util/format-benchmark-record.js

Realized that I didn't check csv-parse package into package.json :(

Updates package.json. Adds csv-parse to dependencies.

---

package.json

Bumping the package version here since I've added eCQM measure data.

[QPPA-606] bump package version to 0.0.32

---

README.md

so that others may confidently publish new versions 🎉

add documentation for publishing

---

package.json
scripts/build-measures

Removing an unwanted line from build-measure script
- no change in measure data json

Fixing build measure data

---

.gitignore
clinical-clusters/clinical-clusters.json
package-lock.json
package.json
scripts/clinical-clusters/ema-clinical-cluster-builder.js
test/clinical-clusters/clinical-clusters-spec.js
util/clinical-clusters/ClaimsClinical_Cluster.csv
util/clinical-clusters/RegistryClinicalCluster.csv

https://jira.cms.gov/browse/QPPQS-443
Summary of changes
```
1)	Registry
a)	Measure 110 is removed from OsteoporisCare
b)	Measure 226 is removed from HeartFailureCare
2)	Claims
a)	Measure 117 is ADDED to EyeCare
b)	NEW Cluster ColonscopyCare
i)	Measure 130 is ADDED to NEW ColonscopyCare cluster
ii)	Measure 425  is ADDED to NEW ColonscopyCare cluster
c)	NEW Cluster EndoscopyandPolyp Surveillance
i)	Measure 185 is ADDED to EndoscopyandPolyp Surveillance
ii)	Measure 320 is ADDED to EndoscopyandPolyp Surveillance
```

Updates to EMA Cluster Measure

---

package.json

Updating the measure data package version.

updating package version

---

clinical-clusters/clinical-clusters.json
package.json
scripts/clinical-clusters/ema-clinical-cluster-builder.js
test/clinical-clusters/clinical-clusters-spec.js

Fixing few issues identified while testing : QPPQS-544

Measure cluster changes

---

measures/measures-data.json
measures/measures-data.xml
package.json
staging/measures-data.json
test/measures/measures-data-spec.js

https://jira.cms.gov/browse/QPPA-1279
says it on the box! I've updated staging/measures-data.json since this is coming directly from CMS and not from any other source document.

update measures 117 and 001 with cmsWebInterface submission method

---

package.json

TIL that if you unpublish, you cannot publish over the previously published version

QPPA-1231 bump version number

---

package-lock.json
package.json

Only changes are adding QCDR single performance rate and non-proportion measures.

Bump version to 1.0.0-alpha.15

---

CONTRIBUTING.md

We want to start maintaining release notes to better communicate what changes are being made.

Release notes instructions

---

CONTRIBUTING.md

Clean up contributing readme and request a descriptive release title.
Reviewer @lamroger

Update contributing readme

---

package.json

We'd like to publish the finalized release of 2017 measures data.
Reviewer: @jiahuang

Version bump to 1.0.0

---

measures/measures-data.json
measures/measures-data.xml
package.json
staging/measures-data-with-qcdrs.json
staging/measures-data.json

This PR fixes a typo in the description of ACI_CCTPE_2
Jira: https://jira.cms.gov/browse/QPPA-1497
Testing: still passes tests
Reviewer: @lamroger @kencheeto

[QPPA-1497] Fix typo in description of ACI_CCTPE_2

---

measures/measures-data.json
measures/measures-data.xml
package-lock.json
package.json
staging/measures-data-with-qcdrs.json
staging/measures-data.json

previously, isInverse for meaure 458 was false. this PR changes that value to true. it is an inverse measure.

QPPA-1733 change value of isInverse for measure 458

---

measures/measures-data.xml

One of the last commits to #108 made some JSON changes that weren't propagated to XML. This PR fixes that.

Update XML after #108

---

measures/measures-data.json
measures/measures-data.xml
package-lock.json
package.json
staging/measures-data-with-qcdrs.json
staging/measures-data.json

Quality measure 420 has been updated to being a high priority measure, and the patch version has been bumped.
Note: updated files in `/staging` directory, ran `npm run build:measures` command, and test and validation pass!

QPPA-1757 Updated Measure 420 to be High Priority

---

measures/measures-data.json
measures/measures-data.xml
measures/measures-schema.yaml
package.json
staging/measures-data-with-qcdrs.json
staging/measures-data.json

https://jira.cms.gov/browse/QPPA-1783
Add MSPB and TPCC to qpp-measures-data.
Test Plan:
Ensure all existing unit tests continue to pass.
Reviewer: @marimiyachi

QPP-1783 add mspb and tpcc to qpp-measures-data

---

measures/2018/measures-data.json
measures/2018/measures-data.xml
util/measures/2018/enriched-measures-data-quality.json
util/measures/2018/manually-created-missing-measures.json

- This is a PR to correct the measure data mistake pointed out by @sarahnw.

Fix measure 226 (CMS138v6)

---

CODEOWNERS

👋 i'm no longer working on this repo, so removing myself as code owner so i don't get tagged on every pr. Still tag me on any questions you have!

remove kencheeto as codeowner

---

benchmarks/2018.json
measures/2018/measures-data.json
measures/2018/measures-data.xml
staging/2018/benchmarks/json/001_benchmarks_wi.json
util/measures/2018/manually-added-measures.json

Add dmComposite and other WI measure benchmarks to measures data. 
- [QPPSF-3093](https://jira.cms.gov/browse/QPPSF-3093)

QPPSF-3093 - dmComposite and WI Benchmarks

---

package-lock.json

There was a change of version made in package.json that was merged. However, package-lock.json was not updated. This PR updates the version in package-lock-json to match.
Reveiewer: @sheldon-b

Update Version in package-lock.json

---

benchmarks/2018.json
package-lock.json
package.json
staging/2018/benchmarks/json/001_benchmarks_wi.json

Uploaded DM Composite WI Benchmarks
---
Uploaded DM Composite WI Benchmarks
Things that have to pass. These are things that the reviewer(s) should be able to reproduce. This can also include a list like:
* https://jira.cms.gov/browse/QPPSF-3093
@kalvinwang @lamroger @NateTheGreatt @bijujoseph @KyleApfel @rockykitamura @marimiyachi @samskeller @kyeah @sheldon-b @shebryant

QPPSF-3093 Uploaded DM Composite WI Benchmarks

---

measures/2019/measures-data.json
measures/2019/measures-data.xml
staging/2019/measures-data-ia.json

When reviewing a previous PR that updated IA measures, Kalvin noticed an inaccuracy in the description for measureId IA_BE_1 in the csv file. I uploaded an updated file that was provided and bumped the version, but didn't actually run the build script to update the measures json before merging. I have since run build and this PR includes the updates for that measure in the measures json file. Once approved, I'll merge and publish.

QPPA-2737: Include Updated IA Measures 

---

CONTRIBUTING.md

Update CONTRIBUTING.md to recommend version bump for any non-doc-only change

Recommend version bump for any non-doc-only change

---

benchmarks/2018.json
package-lock.json
package.json

https://jira.cms.gov/browse/QPPA-2901
Adding 2018 CAHPS benchmarks.

[QPPA-2901] Add 2018 CAHPS benchmarks

---

clinical-clusters/2019/clinical-clusters.json
scripts/clinical-clusters/ema-clinical-cluster-builder.js
util/clinical-clusters/2019/ClaimsClinical_Cluster.csv
util/clinical-clusters/2019/RegistryClinicalCluster.csv

What is the problem being solved? What is the feature being added?
* https://jira.cms.gov/browse/QPPSF-5230
@harrisj @lamroger @sheldon-b @kyeah @shebryant @KyleApfel @NateTheGreatt @Jpec07 @bijujoseph

QPPSF-5230 - Refined Y3 Clinical Clusters

---

benchmarks/2019.json
package-lock.json
package.json
staging/2019/benchmarks/benchmarks.csv
staging/2019/benchmarks/json/benchmarks.json

https://jira.cms.gov/browse/QPPSF-5268
Measure 226 needs to be suppressed on the web interface side.
Measure 226 benchmarks are being removed.

Remove measure 226 benchmarks

---

clinical-clusters/2019/clinical-clusters.json
package.json
scripts/clinical-clusters/ema-clinical-cluster-builder.js
util/clinical-clusters/2019/RegistryClinicalCluster.csv

Removed Special Scenarios for Clinical Clusters
After discussion with BA's, we removed special scenarios for Clinical Clusters.
After discussion with BA's, we removed special scenarios for Clinical Clusters.
* https://jira.cms.gov/browse/QPPA-5346
@harrisj @lamroger @sheldon-b @kyeah @shebryant @KyleApfel @NateTheGreatt @Jpec07 @bijujoseph

QPPSF-5346 - Remove Special Scenarios for Clinical Clusters

---

benchmarks/2019.json
package-lock.json
package.json
staging/2019/benchmarks/benchmarks.csv
staging/2019/benchmarks/json/benchmarks.json

Removed cmsWebInterface 134 benchmark
Benchmarks to be removed:
“submissionMethod”: “*cmsWebInterface*” from “measureId”: “134"
Removed cmsWebInterface 134 benchmark
* https://jira.cms.gov/browse/QPPSF-5662

QPPSF-5662 - Removed cmsWebInterface 134 benchmark

---

measures/2020/measures-data.json
package.json
util/measures/2020/claims-links.csv
util/measures/2020/cqm-links.csv
util/measures/2020/enriched-measures-data-quality.json

Updates were provided for quality and claims measure specification links.
measure specification links updated for the given measures.
* https://jira.cms.gov/browse/QPPA-3721

QPPA-3721: Updated 2020 cqm and claims measure specs

---

.gitignore
index.js
package-lock.json
package.json

Added test coverage report to aid in collecting code metrics.

Adding test coverage report

---

package-lock.json
package.json

Release 1.43.0

---

benchmarks/2020.json
package-lock.json
scripts/benchmarks/helpers/convert-2020-to-csv.js
staging/2020/benchmarks/benchmarks.csv
staging/2020/benchmarks/json/wi-benchmarks.json

There was an error with column ordering in the 2020 source conversion script.
- Fixed error with column ordering in the 2020 source conversion script and regenerated `benchmarks.csv`
- Added WI benchmarks
* https://jira.cms.gov/browse/QPPBSR-7602

2020 script fix and add WI benchmarks

---

.github/workflows/publish.yml

update release action

---

.github/workflows/draft-release.yml
.github/workflows/publish.yml
package.json

action updates

---

CONTRIBUTING.md

Updated the contributing page with debugging tips around Github Actions.
* https://jira.cms.gov/browse/QPPSF-6504

QPPSF-6504 - Add debugging tips for contributors

---

clinical-clusters/2020/clinical-clusters-schema.yaml
clinical-clusters/2020/clinical-clusters.json

Copying 2020 clinical clusters data in order to unblock testing of the Quality pipeline in Scoring Engine for Y4.
Note: needs to be updated with actual 2020 data when received

2020 clinical clusters copy

---

package-lock.json
package.json

Creating v3.1.3 release

---

package.json

Release v3.1.4
2020 clinical cluster data copied from 2019 for SE testing purposes

Release v3.1.4

---

.github/workflows/publish.yml

Automatically create a branch and PR to backfill develop on publishing a new version
* https://jira.cms.gov/browse/QPPA-4231

QPPA-4231 Automatic backfill

---

CONTRIBUTING.md

Describes the PR flow in CONTRIBUTING.md so new developers to the repo know what to expect

adds description of the pull request flow to CONTRIBUTING.md

---

CONTRIBUTING.md

Update documentation to reflect automation changes via github actions
* https://jira.cms.gov/browse/QPPA-4522

QPPA-4522 Update Release/Publishing documentation

---

.github/workflows/publish.yml

@cagedcrown has requested that they be added to the publish notification.
Added `CMSgov/qpp-ui` to the list of repos to notify.

Add qpp-ui repo to publish notification event

---

measures/2020/measures-data.json
scripts/measures/lib/merge-ecqm-data.js
staging/2020/measures-data-quality.json
util/measures/2020/enriched-measures-data-quality.json
util/measures/2020/quality-strata.csv

Measure 370 had invalid descriptions, updating csv to correct one and scripts to always pull description from csv (over eCQM description)
* https://jira.cms.gov/browse/QPPA-4707

QPPA-4707 Load Strata descriptions from strata csv

---

package-lock.json
package.json

Bumped version number to 3.2.2

---

clinical-clusters/2020/clinical-clusters.json
scripts/clinical-clusters/build-clinical-clusters
scripts/clinical-clusters/ema-clinical-cluster-builder.js
util/clinical-clusters/2020/ClaimsClinical_Cluster.csv
util/clinical-clusters/2020/RegistryClinicalCluster.csv

Updates the EMA Clinical Cluster and Speciality Sets generation script for Y4 as they were confirmed recently.
* https://jira.cms.gov/browse/QPPSF-7226

QPPSF-7226: Update 2020 EMA Speciality Sets & Clinical Clusters

---

scripts/measures/lib/merge-benchmark-metadata.js
test/scripts/measures/lib/merge-benchmark-metadata-spec.js

Increase code coverage.
Increase Testing Coverage Main Mocha Suite for measures lib folder
* https://jira.cms.gov/browse/QPPA-4445

QPPA-445: fix test coverage

---

package-lock.json
package.json

Bumped the version number to 4.0.1

---

measures/2021/measures-data.json
util/measures/2021/ecqm-ehr-links.csv
util/measures/2021/enriched-measures-data-quality.json

https://jira.cms.gov/browse/QPPA-4903

QPPA-4903 Fix last two broken ehr links

---

package-lock.json
package.json

Backfill V4.0.2 to develop

---

measures/2020/measures-data.json
util/measures/2020/benchmark-metadata.csv
util/measures/2020/enriched-measures-data-quality.json

Adding measure suppression data for PY2020
* https://jira.cms.gov/browse/QPPA-4849

QPPA-4849 PY2020 Clinical Guidelines Changed

---

benchmarks/2021.json
package.json
scripts/benchmarks/build-benchmarks
scripts/benchmarks/helpers/pre-process-source-csv.js
staging/2021/benchmarks/benchmarks.csv
staging/2021/benchmarks/json/benchmarks.json
staging/2021/benchmarks/source.csv

* Repurpose 2020 conversion script to be usable across multiple years
* Load new 2021 source file for benchmarks
* Remove IRIS2 benchmark removed in previous tickets
* https://jira.cms.gov/browse/QPPA-5142

QPPA-5142: 2021 Benchmark Updates

---

clinical-clusters/2021/clinical-clusters-schema.yaml
clinical-clusters/2021/clinical-clusters.json
package.json

releasing 4.3.1 so that Scoring Engine can test against the mocked clinical clusters data
package.json version bump

Publish Release 4.3.1

---

package.json

To delivery the latest Historical Benchmarking data. Once this release is finalized and delivered, a release v4.5.1 will be generated to pull in Performance Benchmarks.

Publish Release v4.5.0

---

package.json

To deliver the latest PY2020 Performance Benchmarking data.

Update Version Number To 4.5.1

---

package.json

What is the problem being solved? What is the feature being added?
Add Y5 benchmark updates for WI (https://github.com/CMSgov/qpp-measures-data/pull/462)
* https://jira.cms.gov/browse/QPPBSR-8035

Publish Release v4.6.0

---

measures/2021/measures-data.json
util/measures/2021/enriched-measures-data-quality.json
util/measures/2021/manually-created-missing-measures.json

Fix for SN issue
Correct measure 238 (CMS156v9) Uuid's for Year 2021. 
* https://jira.cms.gov/browse/QPPSF-8415

QPPSF-8415: Fix Measure 238 Uuid's

---

measures/2021/measures-data.json
util/measures/2021/benchmark-metadata.csv

Mark clinicalGuidelinesChanged for measures 001 & 117 for the 'claims' submission method
* https://jira.cms.gov/browse/QPPA-5488

QPPA-5488 2021 Measure 001,117 Claims Clinical Guidelines Changed

---

measures/2022/measures-data.json
package-lock.json
package.json
scripts/measures/2022/import-quality-measures.js
staging/2022/measures-data-quality.json
util/measures/2022/enriched-measures-data-quality.json
util/measures/2022/quality-measures.csv

This PR primarily updates the quality measures via the latest measures warehouse for 2022.
It also fixes some character issues (e.g., some dashes and apostrophes were being improperly converted and were removed by the scripts).
* https://jira.cms.gov/browse/QPPA-5566
* https://jira.cms.gov/browse/QPPA-5962

feat: QPPA-5566 updated quality measures 2022

---

scripts/benchmarks/build-benchmarks
scripts/benchmarks/format-benchmark-record.js
scripts/benchmarks/parse-benchmarks-data.js

Update benchmark ingestion scripts to account for MCC benchmarks
* https://jira.cms.gov/browse/QPPA-5620

QPPA-5620 Update script to ingest MCC benchmarks

---

package-lock.json
package.json

QPP Measures Release v5.3.0
QPP Measures Release v5.3.0
* https://jira.cms.gov/browse/QPPSF-9259
* https://jira.cms.gov/browse/QPPA-5620

QPP Measures Release v5.3.0

---

package-lock.json
package.json

QPP Measures Release v5.3.1
QPP Measures Release v5.3.1
* https://jira.cms.gov/browse/QPPSF-9259
* https://jira.cms.gov/browse/QPPA-5620
* https://jira.cms.gov/browse/QPPA-5761

QPP Measures Release v5.3.1

---

measures/2022/measures-data.json
staging/2022/measures-data-pi.json
util/measures/2022/enriched-measures-data-pi.json
util/measures/2022/pi-measures.csv

PI_ONCDIR_1 was not included in 2022 measures, but should be. This PR adds it back.
* https://jira.cms.gov/browse/QPPA-6073

QPPA-6073: Adds PI_ONCDIR_1 2022 measures

---

CONTRIBUTING.md

Updated CONTRIBUTING documentation for versioning

QPPA-0000: update versioning docs

---

benchmarks/2021.json
scripts/benchmarks/parse-benchmarks-data.js
staging/2021/benchmarks/benchmarks_mcc.csv
staging/2021/benchmarks/json/benchmarks_mcc.json

QPPA-5910 Ingest benchmarks for MCC1 measure
Adding benchmarks for MCC1 measure (PY 2021)
Add new benchmarks; update script slightly to avoid processing unnecessary/nonexistent columns
* https://jira.cms.gov/browse/QPPA-5910

QPPA-5910 Ingest benchmarks for MCC1 measure

---

measures/2022/measures-data.json
scripts/measures/2022/import-pi-measures.js
staging/2022/measures-data-pi.json
util/measures/2022/enriched-measures-data-pi.json
util/measures/2022/pi-measures.csv

Updated PI Measures for PY2022.
See ticket below for details on the changes.
* https://jira.cms.gov/browse/QPPA-6418

QPPA-6418: update pi measures 2022

---

measures/2022/measures-data.json
staging/2022/measures-data-pi.json
util/measures/2022/enriched-measures-data-pi.json
util/measures/2022/pi-measures.csv

* https://jira.cms.gov/browse/QPPA-6542

QPPA-6542: added PI_ONCACB_1 for PY2022

---

CONTRIBUTING.md

Updated docs with how to support utf-8 encoding.
* https://jira.cms.gov/browse/QPPA-6435

QPPA-6435: docs for extended ascii support

---

benchmarks/2021.json
scripts/benchmarks/helpers/merge-benchmark-data-helpers.js
staging/2021/benchmarks/json/performance-benchmarks.json

- remove helper trimming
- update measures 479, 480, acep50, acep51
* https://jira.cms.gov/browse/QPPSF-10550

QPPSF-10550: Update Y5 performance benchmarks

---

clinical-clusters/2022/clinical-clusters.json
scripts/clinical-clusters/build-clinical-clusters
scripts/clinical-clusters/ema-clinical-cluster-builder.js
util/clinical-clusters/2022/ClaimsClinical_Cluster.csv
util/clinical-clusters/2022/RegistryClinicalCluster.csv

Update 2022 EMA clinical clusters.
Changes made according to [this wiki page](https://confluence.cms.gov/x/nCWZJw).
* https://jira.cms.gov/browse/QPPA-10673

QPPSF-10673: Update 2022 EMA clinical clusters

---

README.md

Add a temp warning to ignore PY23 data. Ticket QPPA-6908 is created to remove this in the future.
* https://jira.cms.gov/browse/QPPA-6904

QPPA-6904: add py23 psa to readme

---

.github/workflows/benchmark-change.yml

Add slack notification whenever benchmarks are changed (this PR is to test the functionality)
* https://jira.cms.gov/browse/QPPA-6873

QPPA-6873: slack notification benchmark change

---

.github/workflows/benchmark-change.yml

test fix
* https://jira.cms.gov/browse/QPPA-6873

test: QPPA-6873 test

---

.github/workflows/benchmark-change.yml

Complets 6873 by pointing the new Action to CMS Slack
* https://jira.cms.gov/browse/QPPA-6873

QPPA-6873: point to cms slack

---

README.md

QPPA-6938 Update README for filtering MVP data
* https://jira.cms.gov/browse/QPPA-6938

QPPA-6938 Update README for filtering MVP data

---

.gitignore
CONTRIBUTING.md
package-lock.json
package.json
scripts/measures/initialize-measures
scripts/measures/json-to-csv.ts
scripts/measures/measures-json-to-csv
scripts/measures/update-measures

Adds the ability to export measures to a CSVs (by category).
* https://jira.cms.gov/browse/QPPA-6988

QPPA-6988: add export-to-csv feature for measures

---

scripts/measures/json-to-csv.ts

Small fix for the Measures exporter script for qcdrs and quality measures.

QPPA-0000: exporter script fix

---

index.js
measures/2023/measures-data.json
measures/2023/measures-schema.yaml
mvp/2023/mvp-enriched.json

When creating the MVP data file, we also need to update the measures-data.json file to include any relevant MVP IDs to the `allowedPrograms` field on the given measure, if that measure is part of that MVP.
* https://jira.cms.gov/browse/QPPA-6993

QPPA-6993 Update measures data when creating MVP data file

---

index.js
measures/2023/measures-data.json
mvp/2023/mvp-enriched.json
package.json
scripts/mvp/2023/update-mvp.ts
scripts/mvp/update-mvp

If we get an updated mvp.json file we will run this script to update the mvp-enriched.json and the measures-data.json file accordingly.
* https://jira.cms.gov/browse/QPPA-6979

QPPA-6979 Add update-mvp script and logic

---

scripts/measures/update-measures
scripts/mvp/update-mvp

QPPA-6980 Update MVPs when measure data is updated
* https://jira.cms.gov/browse/QPPA-6980

QPPA-6980 Update MVPs when measure data is updated

---

CONTRIBUTING.md

QPPA-6981 Update CONTRIBUTING.md for MVP data ingestion
* https://jira.cms.gov/browse/QPPA-6981

QPPA-6981 Update CONTRIBUTING.md for MVP data ingestion

---

measures/2022/measures-data.json
scripts/measures/2022/get-strata-uuids-from-ecqm-zip.js
util/measures/2022/additional-stratifications.json
util/measures/2022/enriched-measures-data-quality.json
util/measures/2022/generated-ecqm-data.json
util/measures/2022/manually-created-missing-measures.json

[QPPSF-10743](https://jira.cms.gov/browse/QPPSF-10743)
- Y6 eCQM UUIDs (https://ecqi.healthit.gov/sites/default/files/2022-CMS-QRDA-III-Eligible-Clinicians-and-EP-IG-V1.1-508.pdf#page=43)
- Add Y6 eCQM UUIDs data and run the build for the 2022 measures data.

QPPSF-10743: Y6 eCQM UUID Updates

---

benchmarks/2022/benchmarks-schema.yaml
scripts/benchmarks/format-benchmark-record.js
scripts/benchmarks/parse-benchmarks-data.js

QPPA-6971 Update benchmarks schema
* https://jira.cms.gov/browse/QPPA-6971

QPPA-6971 Update benchmarks schema

---

measures/2023/measures-data.json
mvp/2023/mvp-enriched.json
scripts/measures/initialize-measures
scripts/measures/initialize-measures-data.ts
updates/measures/2023/changes.meta.json

Reset Annual fields via the init script and cleanup 2023
* https://jira.cms.gov/browse/QPPA-7165
* https://jira.cms.gov/browse/QPPA-7166

QPPA-7165: reset annual fields and cleanup

---

measures/2023/measures-data.json
scripts/measures/lib/csv-json-converter.ts
updates/measures/2023/Quality_QCDR_PY23_CR_20221209.csv
updates/measures/2023/Quality_QCDR_PY23_CR_20221212.csv
updates/measures/2023/changes.meta.json
util/measures/2023/qcdr-strata.csv

New measure 'AAD16' added.
New measure 'AAD17' added.
New measure 'AAD18' added.
New measure 'AJRR7' added.
New measure 'MBHR18' added.
New measure 'REGCLR8' added.
New measure 'SPINETRACK9' added.
New measure 'AJRR11' added.
New measure 'AJRR8' added.
New measure 'AJRR9' added.
Measure 'UREQA7' removed.
Measure 'UREQA1' removed.
Measure 'QUANTUM31' removed.
Measure 'MBHR17' removed.
Measure 'ASPS27' removed.
Measure 'ASPS28' removed.
Measure 'ASPS29' removed.
Measure 'HCPR18' removed.
Measure 'HCPR14' removed.
Measure 'ECPR41' removed.
Measure 'AQI62' removed.
Measure 'AAO24' removed.
Measure 'AAD13' removed.
Measure 'AAAAI6' removed.
Measure 'REGCLR6' removed.
Measure 'MBHR12' removed.
Measure 'AAD10' removed.
Measure 'AAD9' removed.
Measure 'CAP33' removed.
Measure 'LMBR4' updated. …

QPPA-6823: updated bulk QCDR for PY23

---

measures/2023/measures-data.json

remove PIMSH14 for 2023
* https://jira.cms.gov/browse/QPPA-6823

QPPA-6823: remove PIMSH14

---

README.md
measures/2023/measures-data.json
mvp/2023/mvp-enriched.json
util/measures/2023/quality-strata.csv

Updated the quality strata file for PY23.
Removed warning about PY23 data changes from README.
* https://jira.cms.gov/browse/QPPA-6908
* https://jira.cms.gov/browse/QPPA-7157

QPPA-7157, QPPA-6908: update py23 quality strata

---

measures/2023/measures-data.json
mvp/2023/mvp-enriched.json
updates/measures/2023/Quality_QCDR_PY23_20221216.csv
updates/measures/2023/changes.meta.json
util/measures/2023/qcdr-strata.csv

Measure 'ABG40' updated.
Measure 'ABG41' updated.
Measure 'ABG42' updated.
Measure 'ABG43' updated.
Measure 'ACEP19' updated.
Measure 'ACEP21' updated.
Measure 'ACEP22' updated.
Measure 'ACEP30' updated.
Measure 'ACEP31' updated.
Measure 'ACEP50' updated.
Measure 'ACEP51' updated.
Measure 'ACEP52' updated.
Measure 'ACEP53' updated.
Measure 'ACEP59' updated.
Measure 'ACEP60' updated.
Measure 'ACEP61' updated.
Measure 'ACQR12' updated.
Measure 'ACQR13' updated.
Measure 'ACQR16' updated.
Measure 'ACR12' updated.
Measure 'ACR14' updated.
Measure 'ACR15' updated.
Measure 'ACRAD15' updated.
Measure 'ACRAD16' updated.
Measure 'ACRAD17' updated.
Measure 'ACRAD18' updated.
Measure 'ACRAD19' updated.
Measure 'ACRAD25' updated.
Measure 'ACRAD40' updated.
Measure 'ACRAD42' updated.
Measure 'AQI18' …

QPPA-7209: update py23 QCDR measures and strata

---

measures/2023/measures-data.json
mvp/2023/mvp-enriched.json
mvp/2023/mvp-raw.json
mvp/2023/mvp.json
package.json
scripts/mvp/parse-mvp-data
scripts/mvp/parse-mvp-data.ts

New data came in for MVPs 2023
- Added a script to parse the raw data JSON (it was actually an excel spreadsheet/csv, used an online tool to convert it to JSON)
- Updates the mvp and measure data files accordingly
* https://jira.cms.gov/browse/QPPA-7145

QPPA-7145 New script to parse MVP & new MVP data

---

measures/2023/measures-data.json
measures/2023/measures-schema.yaml
scripts/constants.ts
updates/measures/2023/PI_PY23_CR_20221228.csv
updates/measures/2023/changes.meta.json

New measure 'PI_ONCACB_1' added.
* https://jira.cms.gov/browse/QPPA-7221

QPPA-7221: restore PI_ONCACB_1 for PY 2023

---

measures/2022/measures-data.json
scripts/measures/2022/update-measures-util.ts
updates/measures/2022/Quality_QCDR_PY22_Measure_20021230_Suppressed.csv
updates/measures/2022/changes.meta.json

Suppress measures for PY 2022
Measure '005' updated.
Measure '113' updated.
Measure '134' updated.
Measure '236' updated.
Measure '239' updated.
Measure '281' updated.
Measure '366' updated.
* https://jira.cms.gov/browse/QPPA-6777

QPPA-6777: Update suppressed for PY 2022

---

constants.js
scripts/benchmarks/helpers/pre-process-source-csv.js

QPPA-7254 Add 2023 as valid PY; add deciles 1 and 2
* https://jira.cms.gov/browse/QPPA-7254

QPPA-7254 Add 2023 as valid PY; add deciles 1 and 2

---

measures/2023/measures-data.json
mvp/2023/mvp-enriched.json
scripts/constants.ts
scripts/measures/lib/csv-json-converter.ts
updates/measures/2023/Quality_QCDR_PY23_20230104.csv
updates/measures/2023/Quality_QCDR_PY23_CR_20230105.csv
updates/measures/2023/Quality_QCDR_PY23_CR_20230105_UPDATED.csv
updates/measures/2023/changes.meta.json

Measure '001' updated.
Measure '007' updated.
Measure '008' updated.
Measure '039' updated.
Measure '065' updated.
Measure '066' updated.
Measure '104' updated.
Measure '110' updated.
Measure '111' updated.
Measure '126' updated.
Measure '127' updated.
Measure '134' updated.
Measure '137' updated.
Measure '176' updated.
Measure '177' updated.
Measure '187' updated.
Measure '226' updated.
Measure '238' updated.
Measure '240' updated.
Measure '243' updated.
Measure '305' updated.
Measure '318' updated.
Measure '321' updated.
Measure '326' updated.
Measure '355' updated.
Measure '356' updated.
Measure '379' updated.
Measure '387' updated.
Measure '394' updated.
Measure '402' updated.
Measure '405' updated.
Measure '431' updated.
Measure '453' updated.
Measure '457' updated.
Measure '476' …

QPPA-7252: bulk QCDR and Quality measures update for PY23

---

.github/workflows/publish.yml

[Include any related JIRA issue keys in the PR title, eg `QPPA-1234 Add measures x, y, and z`.](https://jira.cms.gov/browse/QPPA-7271)
Update outdated GitHub Action step in the publish action
Refreshing outdated authorization
* [ X ] Unit tests added/passing

QPPA-7271 Final Update to repo dispatch GitHub Action

---

benchmarks/2022/benchmarks-schema.yaml
benchmarks/2023/benchmarks-schema.yaml
scripts/benchmarks/format-benchmark-record.js
scripts/benchmarks/parse-benchmarks-data.js
test/scripts/benchmarks/fixtures/test-benchmarks.csv
test/scripts/benchmarks/format-benchmark-record-spec.js

- failing tests needed to pass by updating the scripts to process with both 2022 and 2023 csv files
* https://jira.cms.gov/browse/QPPA-7260

QPPA-7260: Clean up benchmarks scripts to support 2023 and 2022 data

---

measures/2022/measures-data.json

Update 484 to be Inverse.
Add CQM to be suppressed for 238.
* https://jira.cms.gov/browse/QPPA-7293
* https://jira.cms.gov/browse/QPPA-7296

QPPA-7296, QPPA-7293: update measures py22

---

.github/workflows/publish.yml
.github/workflows/test-publish/README.md

For publish GitHub Action: Changed the level at which some if-conditionals are eval'ed

QPPA-7271 Changed the level at which some if-conditionals are eval'ed

---

measures/2023/measures-data.json
mvp/2023/mvp-enriched.json
updates/measures/2023/Qualtiy_QCDR_PY23_CR_20230130.csv
updates/measures/2023/changes.meta.json

Measure '048' updated.
Measure '178' updated.
* https://jira.cms.gov/browse/QPPA-7331

QPPA-7331: specialty set update 2023

---

measures/2023/measures-schema.yaml

Update measures schema for 2023
* https://jira.cms.gov/browse/QPPA-7372

QPPA-7372: update measures schema 2023

---

measures/2022/measures-data.json
measures/2023/measures-data.json
mvp/2023/mvp-enriched.json
updates/measures/2022/Quality_QCDR_PY22_Measure_20220216.csv
updates/measures/2022/changes.meta.json
updates/measures/2023/Quality_QCDR_PY23_20230216.csv
updates/measures/2023/changes.meta.json

QPPA-7456+7457 Updating metricType for measure 483
* https://jira.cms.gov/browse/QPPA-7456
* https://jira.cms.gov/browse/QPPA-7457

QPPA-7456+7457 Updating metricType for measure 483

---

measures/2023/measures-data.json

---
https://jira.cms.gov/browse/QPPA-7841
---
---
---
---

QPPA-7841: Update measure IA-BMH_13 description to reflect suspension

---

mvp/2023/mvp-enriched.json
mvp/2023/mvp-schema.yaml
mvp/2023/mvp.json

---
https://jira.cms.gov/browse/QPPA-7586
---
Remove allowedVendor from adminClaims for MVP.
---
---
---

QPPA-7586: Remove allowedVendor from adminClaims for MVP

---

index.js

---
https://jira.cms.gov/browse/QPPA-8036
---
---
---
---
---
---

QPPA-8036 Provide method to return mvp data with measureIds

---

clinical-clusters/2023/clinical-clusters-schema.yaml
clinical-clusters/2023/clinical-clusters.json
scripts/clinical-clusters/build-clinical-clusters
scripts/clinical-clusters/ema-clinical-cluster-builder.js
util/clinical-clusters/2023/ClaimsClinical_Cluster.csv
util/clinical-clusters/2023/RegistryClinicalCluster.csv

- Update 2023 Specialty Sets
- Clinical Clusters remains a copy of 2022 until updated 2023 Clinical Cluster data is provided.
---
https://jira.cms.gov/browse/QPPSE-935
---
---
---
---

[QPPSE-935] Update 2023 Clinical Clusters

---

measures/2023/measures-data.json
mvp/2023/mvp-enriched.json

---
https://jira.cms.gov/browse/QPPA-8064
---
---
---
---
---

QPPA-8064: update allowed programs non quality 2023

---

.github/workflows/pr-feature.yml
package.json
scripts/benchmarks/validation.business.spec.ts
scripts/measures/2022/update-measures-util.spec.ts
scripts/measures/2023/update-measures-util.spec.ts

---
---
Tests updated and jest tests added to PR coverage check
---
---
---
---

QPPA-0000 update tests

---

benchmarks/2023/benchmarks-schema.yaml
measures/2023/measures-schema.yaml
measures/2024/measures-schema.yaml
mvp/2023/mvp-schema.yaml
package-lock.json

---
https://jira.cms.gov/browse/QPPA-8070
---
---
---
---

QPPA-8070: Corrects invalid formatting in yaml files

---

clinical-clusters/2023/clinical-clusters.json
util/clinical-clusters/2023/ClaimsClinical_Cluster.csv
util/clinical-clusters/2023/RegistryClinicalCluster.csv

---
https://jira.cms.gov/browse/QPPSE-1098
---
---
---
---
---
---

Qppse 1098 - Fix 2023 Clinical Clusters

---

benchmarks/2023/benchmarks-exclusion-reasons-schema.yaml

---
https://jira.cms.gov/browse/QPPA-8025
---
---
---
---
---
---

QPPSE-671: Add benchmark exclusion reasons schema

---

index.js
scripts/measures/initialize-measures
scripts/mvp/parse-mvp-data.ts
scripts/mvp/update-mvp

---
https://jira.cms.gov/browse/QPPA-7749
---
Update MVP script logic to handle `administrativeClaimsMeasures`, `hasCahps`, and `hasOutcomeAdminClaims`.
---
---
---
---

QPPA-7562: Update MVPs with new fields

---

measures/2023/measures-data.json
measures/2024/measures-data.json

---
https://jira.cms.gov/browse/QPPA-8245
---
update measure PI_HIE_5 & PI_HIE_6
---
---
---

QPPA-8245: update measure PI_HIE_5 & PI_HIE_6

---

scripts/benchmarks/build-benchmarks

QPPA-0000: Update Benchmarks max year to 2024

---

measures/2023/measures-data.json

---
https://jira.cms.gov/browse/QPPA-7842
---
---
---
---

QPPA-7842: remove IA_BMH_13 from PY2023 measures

---

.github/workflows/draft-release.yml
.github/workflows/pr-feature.yml
.github/workflows/pr-release.yml
.github/workflows/publish.yml

---
https://jira.cms.gov/browse/QPPA-8359
---
---
---
---
---

QPPA-8359: Update supporting Github Actions versions

---

index.js

---
---
Add getter function for Benchmarks exclusion reasons
---
---
---
---

QPPA-0000: Add getter function for Benchmarks exclusion reasons

---

benchmarks/2023/benchmark-exclusion-reasons.json

---
https://jira.cms.gov/browse/QPPA-1428
---
QPPSE-1428: Update any measure: submissionMethod having BR-002 and BR-007 to the reason code BR-009
---
---
---
---
---

QPPSE-1428: Update any measure: submissionMethod having BR-002 and BR-007 to the reason code BR-009

---

scripts/measures/export-measures

---
---
Update export script for PY2024 and to work on PC
---
---
---
---

QPPA-0000: update export script

---

measures/2023/measures-data.json
mvp/2023/mvp-enriched.json
updates/measures/2023/Qualtiy_QCDR_PY23_CR_Truncated_20231201.csv
updates/measures/2023/changes.meta.json

---
https://jira.cms.gov/browse/QPPA-8454
---
Measure '006' updated.
Measure '007' updated.
Measure '052' updated.
Measure '243' updated.
Measure '290' updated.
Measure '291' updated.
Measure '293' updated.
---
---
---

QPPA-8454: truncate some PY23 measures

---

CONTRIBUTING.md
measures/2024/measures-data.json
mvp/2024/mvp-enriched.json
util/measures/2024/qcdr-strata.csv
util/measures/2024/quality-strata.csv

https://jira.cms.gov/browse/QPPA-8301
---
---
---
---

QPPA-8301: Stratum updates + Minor Readme change

---

benchmarks/2024/benchmarks-exclusion-reasons.json

https://jira.cms.gov/browse/QPPSE-1625
---
---
---
---
---
---

QPPSE-1625: Remove PP11 from exclusion reasons

---

measures/2024/measures-data.json
mvp/2024/mvp-enriched.json
updates/measures/2024/Quality_QCDR_PY2024_CR_RepoReview_01162024.csv
updates/measures/2024/Quality_QCDR_PY24_CR_20240118.csv
updates/measures/2024/changes.meta.json

https://jira.cms.gov/browse/QPPA-8628
---
Measure '012' updated.
Measure '137' updated.
Measure '394' updated.
Measure 'AAN9' updated.
Measure 'ABFM12' updated.
Measure 'IRIS50' updated.
Measure 'MSN15' updated.
Measure 'NHCR4' updated.
Measure 'AAN22' updated.
Measure 'AAN25' updated.
Measure 'AAN31' updated.
Measure 'AAN32' updated.
Measure 'AAN34' updated.
Measure 'AAN35' updated.
Measure 'AAN36' updated.
Measure 'AAN5' updated.
Measure 'AAN8' updated.
Measure 'AAN9' updated.
Measure 'ABG42' updated.
Measure 'ABG44' updated.
Measure 'HCPR25' updated.
Measure 'GIQIC26' updated.
---
---
---
---
---

feat: QPPA-8628 update quality measures 2024

---

README.md

https://jira.cms.gov/browse/QPPA-8097
---
---
---
---
---
---

QPPA-8097: Remove 2024 warning

---

scripts/measures/2023/ingest-strata.ts
scripts/measures/2024/ingest-strata.ts
util/measures/2023/quality-strata.csv

https://jira.cms.gov/browse/QPPA-8483
---
---
---
---
---
---

QPPA-8483: Add rate x removal for measures strata

---

scripts/measures/2023/get-strata-uuids-from-ecqm-zip.js

https://jira.cms.gov/browse/QPPSE-1530
---
Updated automation scripts to handle eCQM parsing to avoid any manual process
---
---
---

QPPSE-1530: Updated automation scripts to handle eCQM parsing to avoid any manual process

---

measures/2023/measures-data.json
measures/2024/measures-data.json
mvp/2023/mvp-enriched.json
mvp/2024/mvp-enriched.json
util/measures/2023/quality-strata.csv
util/measures/2024/claims-links.csv
util/measures/2024/cqm-links.csv
util/measures/2024/quality-strata.csv

https://jira.cms.gov/browse/QPPA-8680
https://jira.cms.gov/browse/QPPA-8681
---
---
---
---
---
---

QPPA-8680, QPPA-8681: update some strata descriptions for PY23 and PY24

---

measures/2024/measures-data.json
updates/measures/2024/Cost_Measures_CR_20240208-1.csv
updates/measures/2024/changes.meta.json

https://jira.cms.gov/browse/QPPA-8697
---
---
---
---
---
---

QPPA-8697: PY24 - Remove COST_SPH_1

---

package-lock.json
package.json

Backfill v7.0.5 to develop

---

scripts/measures/2024/update-measures-util.ts

https://jira.cms.gov/browse/QPPA-8744
---
---
---
---
---
---

QPPA-8744: deep-delete measureIds

---

measures/2024/measures-data.json
package-lock.json
util/measures/2024/claims-links.csv

https://jira.cms.gov/browse/QPPA-8792
---
update measure spec link for measure 181
---
---
---

QPPA-8792: update measure spec link for measure 181

---

.github/release-drafter.yml

https://jira.cms.gov/browse/QPPA-8917
---
---
---
---
- `notes:*`
- `version:*`

QPPA-8917: cleans up formatting of draft release

---

.github/workflows/publish.yml

https://jira.cms.gov/browse/QPPA-9007
---
---
---
---
- `notes:*`
- `version:*`

QPPA-9007: Update Github Action for minor fixes and improvements

---

measures/2024/measures-data.json
mvp/2024/mvp-enriched.json
util/measures/2024/cost-links.csv

https://jira.cms.gov/browse/QPPA-9105
---
update measure spec link for copd measures
---
---
---
- `notes:measure-update`
- `version:*`
---
---

QPPA-9105: update measure spec link for copd

---

index.js
index.spec.ts
package.json

https://jira.cms.gov/browse/QPPA-8978
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-8978: Add unit tests for index.js

---

package-lock.json
package.json

---
fs-extra should be a package dependency but it's listed as a devDependency (meaning it doesn't get packaged in a release).
---
---
---
- `notes:*`
- `version:*`

QPPA-0000: fix for fx-extra package

---

measures/2024/measures-data.json
mvp/2024/mvp-enriched.json
util/measures/2024/quality-strata.csv

https://jira.cms.gov/browse/QPPA-9168
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9168: Remove AveChg stratum from measure 503 PY 2024

---

measures/2023/measures-data.json
mvp/2023/mvp-enriched.json
package-lock.json
util/measures/2023/cost-links.csv

https://jira.cms.gov/browse/QPPA-9290
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9290: Update measure specifications for COST_NECABG_1 and COST_STEMI_1

---

measures/2024/measures-data.json
measures/2024/measures-schema.yaml
mvp/2024/mvp-enriched.json
scripts/constants.ts
scripts/measures/lib/measures-lib.spec.ts
scripts/measures/lib/measures-lib.ts
scripts/measures/lib/validate-change-requests.ts

https://jira.cms.gov/browse/QPPA-9264
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9264: Add new companionMeasureId field

---

.github/workflows/publish-beta-version.yml

https://jira.cms.gov/browse/QPPA-9309
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9309: Add beta versioning

---

.github/workflows/publish-beta-version.yml

https://jira.cms.gov/browse/QPPA-9309
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9309: fix slack notification for beta release

---

constants.ts
index.ts
package.json
scripts/benchmarks/archive/build-benchmarks
scripts/benchmarks/build-benchmarks
scripts/benchmarks/csv-json-converter.ts
scripts/benchmarks/merge-benchmark-files.ts
scripts/clinical-clusters/build-clinical-clusters
scripts/measures/export-measures
scripts/measures/initialize-measures
scripts/measures/update-measures
scripts/mvp/parse-mvp-data
scripts/mvp/update-mvp
scripts/validate-data.ts
tsconfig.json

https://jira.cms.gov/browse/QPPA-9027
---
Roll back typing in the index.ts file since this will be a major breaking change.
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9027: fix TS migration

---

index.spec.ts
index.ts
scripts/mvp/2023/update-mvp.ts
scripts/mvp/2024/update-mvp.ts
scripts/mvp/2025/update-mvp.ts
util/interfaces/benchmarks.ts
util/interfaces/index.ts
util/interfaces/mvp.ts
util/interfaces/program-names.ts
util/mvp-data-utils.ts

https://jira.cms.gov/browse/QPPA-9423
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9423: Adds strong typing to index.ts

---

util/interfaces/benchmarks.ts

https://jira.cms.gov/browse/QPPA-9423
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9423: fix benchmark type

---

index.ts
util/mvp-data-utils.ts

Corrects file path mapping within the mvp-data util
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-0000: Remove /dist from filepath

---

.github/workflows/publish.yml

feat: QPPA-0000 fix publish build

---

package.json

QPPA-0000: revert package main change

---

measures/2024/measures-data.json
package-lock.json
updates/measures/2024/Quality_Truncated_PY24_CR_20241002.csv
updates/measures/2024/changes.meta.json

https://jira.cms.gov/browse/QPPA-9589
---
update truncated measures
---
---
---

QPPA-9589: PY24 Load ICD10 Updates (truncated measures)

---

measures/2025/measures-data.json
mvp/2025/mvp-enriched.json

https://jira.cms.gov/browse/QPPA-9606
---
remove eMeasureUuid /eMeasureUuids values
---
---
---

QPPA-9606: remove eMeasureUuid /eMeasureUuids for PY25

---

scripts/measures/initialize-measures-data.ts

https://jira.cms.gov/browse/QPPA-9605
---
update initialize-measures-data script
---
---
---

QPPA-9605: update initialize-measures-data script

---

measures/2024/measures-data.json
measures/2025/measures-data.json
updates/measures/2024/QCDR_2024_ABFM13_AnalyticUpdate_CR_10042024.csv
updates/measures/2024/changes.meta.json
updates/measures/2025/QCDR_2025_ABFM13_AnalyticUpdate_CR_10042024.csv
updates/measures/2025/changes.meta.json

https://jira.cms.gov/browse/QPPA-9615
https://jira.cms.gov/browse/QPPA-9619
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9615, QPPA-9619: Update ABFM13 metric type

---

measures/2024/measures-data.json
updates/measures/2024/Quality_PY24_CR_10182024.csv
updates/measures/2024/changes.meta.json

https://jira.cms.gov/browse/QPPA-9634
---
---
---
---

QPPA-9634: Update PY24 418 description

---

measures/2024/measures-data.json
mvp/2024/mvp-enriched.json
util/measures/2024/cqm-links.csv

https://jira.cms.gov/browse/QPPA-9648
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9648: remove space from spec links

---

measures/2025/measures-data.json
measures/2025/measures-schema.yaml
mvp/2025/mvp-enriched.json
mvp/2025/mvp-schema.yaml
scripts/measures/initialize-measures-data.ts

https://jira.cms.gov/browse/QPPA-9665
---
update schema and initialization script related to topped out benchmarks
---
---
---

QPPA-9665: update schema and initialization script

---

measures/2025/measures-data.json
measures/2025/measures-schema.yaml
mvp/2025/mvp-enriched.json
mvp/2025/mvp-schema.yaml
scripts/measures/2022/update-measures-util.ts
scripts/measures/2023/update-measures.ts
scripts/measures/2024/update-measures.ts
scripts/measures/2025/update-measures.spec.ts
scripts/measures/2025/update-measures.ts
scripts/measures/lib/validate-change-requests.ts
test/measures/2025/iaMeasures.csv

https://jira.cms.gov/browse/QPPA-9664
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9664: Remove weight for IA 2025

---

measures/2024/measures-data.json
mvp/2024/mvp-enriched.json
updates/measures/2024/Quality_2024_Suppression488_CR_10292024.csv
updates/measures/2024/changes.meta.json

https://jira.cms.gov/browse/QPPA-9663
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9663: PY24 suppress 488 eCQM

---

scripts/constants.ts
scripts/measures/lib/measures-lib.spec.ts
scripts/measures/lib/measures-lib.ts
scripts/measures/lib/validate-change-requests.ts

https://jira.cms.gov/browse/QPPA-9666
---
update ingestion mappings for isSevenPointCapRemoved and sevenPointCapRemoved
---
---
---

QPPA-9666: update ingestion mapping 

---

measures/2024/measures-data.json
measures/2025/measures-data.json
mvp/2024/mvp-enriched.json
mvp/2025/mvp-enriched.json

https://jira.cms.gov/browse/QPPA-9682
https://jira.cms.gov/browse/QPPA-9683
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9682, QPPA-9683: remove mips and app1 from IA_MVP for PYs 24 and 25

---

package-lock.json
package.json

---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-0000; Move pre-commit to dev dependencies.

---

scripts/measures/export-measures
scripts/measures/initialize-measures

https://jira.cms.gov/browse/QPPA-9710
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9710: Fix measures exporter

---

measures/2024/measures-data.json
mvp/2024/mvp-enriched.json

https://jira.cms.gov/browse/QPPA-9759
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9759: Add PCF to all IA measures of PY24

---

measures/2025/measures-data.json
mvp/2025/mvp-enriched.json
package-lock.json

https://jira.cms.gov/browse/QPPA-9736
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9736: AllowedPrograms update for Cost and IA PY25

---

CONTRIBUTING.md
package.json
scripts/measures/manage-allowed-programs.ts
updates/measures/2025/changes.meta.json

https://jira.cms.gov/browse/QPPA-9758
---
Create a script to add/remove a program to all measures in a given category
---
---
---

QPPA-9758: create script to manage allowed program

---

CONTRIBUTING.md

---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-0000: Update CONTRIBUTING.md

---

index.spec.ts
index.ts
util/update-program-names.spec.ts
util/update-program-names.ts

https://jira.cms.gov/browse/QPPA-9863
---
---
---
---
- `notes:*`
- `version:*`

QPPA-9863: Move updateProgramNames logic to util directory

---

scripts/mvp/2023/update-mvp.ts
scripts/mvp/2024/update-mvp.ts
scripts/mvp/2025/update-mvp.ts

---
Bug fix - adds correction for updateProgramNames import
---
---
---
- `notes:*`
- `version:*`

QPPA-0000: updateProgramNames import correction

---

measures/2025/measures-data.json
mvp/2025/mvp-enriched.json
scripts/constants.ts
scripts/measures/2022/update-measures-util.spec.ts
scripts/measures/lib/measures-lib.spec.ts
scripts/measures/lib/measures-lib.ts

https://jira.cms.gov/browse/QPPA-9852
review ingestion logic for updates to existing measures
---
---
---

QPPA-9852: review ingestion logic for updates to existing measures

---

scripts/constants.ts
scripts/measures/lib/measures-lib.spec.ts
scripts/measures/lib/measures-lib.ts

https://jira.cms.gov/browse/QPPA-9735
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9735: Update default allowedPrograms

---

.github/PULL_REQUEST_TEMPLATE.md

---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-0000: Update PR template

---

README.md
measures/2025/measures-data.json

https://jira.cms.gov/browse/QPPA-9918
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9918: Remove app1 from SSP measures PY25

---

measures/2025/measures-data.json
measures/2025/measures-schema.yaml
mvp/2025/mvp-enriched.json
scripts/benchmarks/benchmarks.types.ts
scripts/constants.ts
scripts/measures/lib/validate-change-requests.ts
util/interfaces/measure.ts

https://jira.cms.gov/browse/QPPA-9729
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9729: Remove overallAlgorithm from cost measures

---

measures/2025/measures-data.json
measures/2025/measures-schema.yaml
mvp/2025/mvp-enriched.json
mvp/2025/mvp-schema.yaml
package-lock.json
scripts/constants.ts
scripts/measures/2022/update-measures-util.spec.ts
scripts/measures/lib/measures-lib.spec.ts
updates/measures/2025/changes.meta.json

https://jira.cms.gov/browse/QPPA-9816
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-9816: Add allowedRegistrationTypes field to PY25 measures

---

benchmarks/2024.json
benchmarks/2024/benchmark-exclusion-reasons.json
staging/2024/benchmarks/benchmarks.csv
staging/2024/benchmarks/json/benchmarks.json

https://jira.cms.gov/browse/QPPSE-2979
https://jira.cms.gov/browse/QPPSE-3677
---
- Remove 389/registry for PY24
- Add BR-022 for 389/registry and 488/EHR
---
---
---
- `notes:*`
- `version:*`
---
---

QPPSE-2979 & 3677: Remove suppressed PY24 benchmarks and update exclusion reasons

---

measures/2025/measures-data.json
mvp/2025/mvp-enriched.json
package-lock.json
scripts/measures/2025/get-stratifications.js
util/measures/2025/additional-stratifications.json
util/measures/2025/generated-ecqm-data.json

https://jira.cms.gov/browse/QPPA-10097
---
---
---
---
- `notes:*`
- `version:*`

QPPA-10097: Updates measures data with PY25 QRDA-III UUIDs

---

.github/workflows/stale-pr-check.yml

---
The stale-pr-check Action used an older version of `sonia-corporation/stale` that still used Projects (classic) which was turned off on April 1st 2025. This PR updates to the latest version of sonia which has migrated to the new Projects.
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-0000: fix GH action for stale PRs

---

measures/2025/measures-data.json
mvp/2025/mvp-enriched.json
util/measures/2025/pi-links.csv

https://jira.cms.gov/browse/QPPA-10458
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-10458: Update PY25 PI Spec URL

---

.github/workflows/sonarqube.yml
sonar-project.properties

https://jira.cms.gov/browse/QPPA-10373
---
This PR adds SonarQube analysis to the project by introducing:
A new GitHub Actions workflow (.github/workflows/sonarqube.yml) that triggers SonarQube scans on PRs to develop via AWS CodeBuild.
A SonarQube configuration file (sonar-project.properties) specifying project and scan settings.
---
---
---

QPPA-10373: add sonarqube yaml

---

measures/2025/measures-data.json
mvp/2025/mvp-enriched.json
package-lock.json
scripts/mvp/2025/update-mvp.ts
util/measures/2025/cost-links.csv

https://jira.cms.gov/browse/QPPA-10539
---
---
---
---
- `notes:*`
- `version:*`
---
---

QPP-10539: Update Spec Link PY25 COST

---

.github/workflows/publish-beta-version.yml
.github/workflows/publish.yml

none
---
Token expired after five years, testing a new one.
---
---
---
- `notes:*`
- `version:*`
---
---

QPPA-0000: Update NPM Token

---

.github/workflows/pr-feature.yml
.github/workflows/publish-beta-version.yml

https://jira.cms.gov/browse/QPPA-9960
---
---
---
---
- `notes:*`
- `version:*`
---
---

feat: QPPA-9960 add beta protection
