CMSgov/qpp-measures-data

.gitignore, README.md
The rich diff illustrates the fix here; I botched something with github markdown in https://github.com/CMSgov/qpp-measures-data/pull/32. Not really sure why the extra nesting on just the code fences for step 3 are necessary 🤷‍♂️
=> fix readme formatting

package.json
I mistakenly moved yamljs to `devDependencies` in https://github.com/CMSgov/qpp-measures-data/pull/32/commits/5cabba29e25e1d87758e750b5b9dee63e5938a55 - this needs to be a `dependency`.
cc @sietekk @bijujoseph
=> move yamljs to dependencies

package.json
0.0.34 was published without bumping the version in package.json, so going to bump to 0.0.35 so I can publish 0.0.35.
=> bumps version to 0.0.35

measures/measures-data.json, measures/measures-data.xml, package.json, scripts/find-ecqms-with-missing-data.js, scripts/get-strata-and-uuids-from-ecqm-zip.js, util/generated-ecqm-data.json, util/manually-added-ecqm-data.json
https://jira.cms.gov/browse/QPPA-743
The `CMSXvY_Simple.xml` files included UUIDs for denominator exception and exclusion fields that were marked as 'None'. I've refactored `get-strata-and-uuids-from-ecqm-zip.js` to parse the `CMSXvY.xml` files instead, which only provide the UUIDs in the [reference PDF](https://www.cms.gov/Regulations-and-Guidance/Legislation/EHRIncentivePrograms/Downloads/eCQM_QRDA_EC.pdf
). I've also updated 145v5 and 160v5 since those were manually pulled, removing the UUIDs for denominator fields that are blank.
I have verified that all of the changes to measures-data in this pr are correct when comparing to the reference PDF, so I only need review for the script changes 🙏
=> [QPPA-743] Ignore empty denom exceptions/exclusions from eCQM zip

README.md
Very (VERY) simple update to the README to fix the usage of `qppMeasuresData.getBenchmarksData` to no longer take the performance year as a parameter (removed in commit 67dca947f6bc5f1736d07441a6895e8f6b66c802).
=> Updates README.md to use correct library calls

benchmarks/2017.json, package.json, scripts/benchmarks/format-benchmark-record.js, test/scripts/benchmarks/format-benchmark-record-spec.js
For topped out measures with only 0-100 or 100-0 (inverse), deciles should either be:
[0, 0, 100, 100, 100, 100, 100, 100, 100]
or 
[100, 100, 0, 0, 0, 0, 0, 0, 0]
The decile array starts at decile 2 and ends at decile 10.  In the regular (non-inverse) case, a performance rate of zero places the measurement below decile 3, a performance rate above zero (but not 100) places the measurement in decile 3, and a performance rate of 100 places the measurement in decile 10.
This is now consistent with other variations of topped out measures.
=> QPPQS 442 additional correction to topped out measures

package.json
Accidentally duplicated the version property during a merge conflict on #85 yesterday and didn't notice. Fixing now.
Reviewers: anyone
=> Fix duplicate version in package.json

package.json
In #88, I should have bumped the version to 1.0.0-alpha.17 since I'd already published 1.0.0-alpha.16 in #85, and npm doesn't allow re-publishing with the same version number. This fixes it.
Reviewers: anyone
=> Bump version to 1.0.0-alpha.17

measures/measures-data.json, measures/measures-data.xml, measures/measures-schema.yaml, scripts/measures/import-qcdr-measures.js, staging/measures-data-with-qcdrs.json
QCDR measures in measures-data.json should include the submissionmethods field, which should equal ['registry']. This PR fixes that and makes submissionmethods a required field.
Jira: https://jira.cms.gov/browse/QPPA-1350
Tests: passes all tests
Reviewer: @marimiyachi
=> [QPPA-1350] Add submissionmethods = registry to QCDR measures

CONTRIBUTING.md, README.md, package.json
Two things:
1) This PR bumps the version number which I should've done in #93
2) This PR updates the contributing readme to clarify when the version number needs to be bumped
Reviewer: @kencheeto @lamroger
=> Bump version and update readme

.travis.yml, claims-related/Makefile, claims-related/README.md, claims-related/scripts/__init__.py, claims-related/tests/test_single_source_conversion_helpers.py
When we moved the claims-based measure enrichment step into this repository, the unit tests got left behind. 
This PR re-introduces the unit tests for local development, but doesn't add them to CI. Because the tests run inside Docker and (AFAIK) Travis doesn't support container caching, including these tests in CI could result in significantly slower build times. Even if they don't run through Travis, I think it makes sense to have them in the repository for development purposes.
=> Add support for running test suite for claims-based measures

README.md
Year currently defaults to 2017 and should until we finish adding 2018 data.
Reviewer: @kyeah
=> Fix readme year

package-lock.json, package.json
https://nvd.nist.gov/vuln/detail/CVE-2018-1002204
Not a likely attack vector for us since we manually process zip files, but upgrades adm-zip anyway to resolve the sec warning that GitHub displays.
=> upgrade adm-zip to fix vulnerability

test/measures/measures-specification-spec.js
the test we merged recently to check that the measure specification links are valid failed because of a timeout, so I'm increasing the timeout here by 50%.
this test only runs on CI during cron runs, once a day.
failing run here:
https://travis-ci.org/CMSgov/qpp-measures-data/jobs/412016666
=> increase test timeout for link checking

package-lock.json, package.json
The version has been changed to 1.8.4 in package.json in preparation for publishing 2018 benchmarks.
=> QPPA 1435 - Bump Version in package.json

clinical-clusters/2018/clinical-clusters.json, package-lock.json, package.json, scripts/clinical-clusters/ema-clinical-cluster-builder.js
The metadata for two claims specialty sets were incorrect (dermatology and neurosurgical), as a result the scoring engine was not reporting these groups of measures as EMA eligible.
https://jira.cms.gov/browse/QPPSF-3067
https://confluence.cms.gov/display/QPPPRACTICE/2018+EMA+Logic+and+Set
```
{ name: 'dermatology', measureIds: ['130', '226', '317'] },
{ name: 'neurosurgical', measureIds: ['021', '023', '130', '226'] }
```
=> QPPSF-3067: Fix 2018 EMA specialty sets for dermatology and neurosurgical

benchmarks/2018.json, package-lock.json, package.json, staging/2018/benchmarks/json/002_benchmarks_aco_cahps.json
Adding ACO CAHPS Benchmarks for 2018 measures.
[QPPSF-3108](https://jira.cms.gov/browse/QPPSF-3108)
=> QPPSF-3108 - Add ACO CAHPS Benchmarks 2018

package-lock.json, package.json, test/measures/2018/measures-data-spec.js
New changes were introduced in previous PR, #177, that require a version bump. This PR updates the version.
=> Update QPP Measures Data Version

CONTRIBUTING.md
Rather than manually updating package.json and package-lock.json.
Previously the version in package-lock.json was getting out of date from
package.json.
`npm version` takes one argument, one of: patch, minor, or major. It
will update the version number in package.json and package-lock.json and
commit the changes in a git commit.
=> Add instructions for using npm version

benchmarks/2018.json, package-lock.json, scripts/benchmarks/format-benchmark-record.js, staging/2018/benchmarks/json/003_benchmarks_updates.json, test/scripts/benchmarks/format-benchmark-record-spec.js
Fix for benchmarks for measures where deciles should be `[100, 0, 0, 0, 0, 0, 0, 0, 0]` (inverse) or `[0, 100, 100, 100, 100, 100, 100, 100, 100]` (regular)
- Updated `scripts/benchmarks/format-benchmark-record.js` so future runs of the `parse-benchmarks-data.js` script produce the correct output
This change affects benchmarks for the following measures/submission methods in 2018:
```
[
["019", "claims"],
["023", "claims"],
["067", "registry"],
["069", "registry"],
["099", "claims"],
["100", "claims"],
["100", "registry"],
["141", "claims"],
["224", "registry"],
["225", "registry"],
["249", "claims"],
["249", "registry"],
["251", "claims"],
["251", "registry"],
["262", "registry"],
["378", "electronicHealthRecord"],
["388", "registry"],
["427", "registry"]
]
```
Related Tickets: …
=> QPPSF-3743 topped out benchmarks for 2018 fix

measures/2018/measures-data.json, measures/2018/measures-data.xml, package.json, staging/2018/measures-data-quality.json, util/measures/2018/enriched-measures-data-quality.json, util/measures/2018/manually-created-missing-measures.json
- The 2018 UUID for eMeasure CMS160v6 had an old UUID from 2017.
- This PR updates the 2018 eMeasureUuid for CMS160v6 to the correct value from the 2018 Implementation Guide.
- The UUID was updated in `util/measures/2018/manually-created-missing-measures.json` and used in the `build-measures.sh`  into `measures/2018/measures-data.json` 
- The description was update to use `\r` instead of `/n` that seems to be included from a separate change.
=> Fix CMS160v6 uuid

clinical-clusters/2018/clinical-clusters.json, package-lock.json, package.json, scripts/clinical-clusters/ema-clinical-cluster-builder.js, test/clinical-clusters/clinical-clusters-spec.js
Removed registry Preventive Care cluster for measure 317 in 2018, that was falsely identifying measures 130, 317 as EMA Cluster
Things that have to pass; these are things that the reviewer(s) should be able to reproduce:
* Ticket - https://jira.cms.gov/browse/QPPSF-4286
Reviewers:
@kalvinwang @KyleApfel @bijujoseph @sheldon-b @kyeah
=> Removed EMA Preventive Care cluster for measure 317 in 2018

.github/PULL_REQUEST_TEMPLATE.md
Use an absolute patch instead of relative. The relative link doesn't work when browsing in github.
=> Update link to version bump info

index.js, package-lock.json, package.json, test/clinical-clusters/clinical-clusters-spec.js
Fixed Clinical Cluster Exception for missing 2019 clusters
Currently receiving error for 2019 Clinical Cluster which will be added later. Discussed with @bijujoseph we decided it would be best that the measures data return an empty array instead of throwing an exception for years that are not found. 
Modified index.js... exports.getClinicalClusterData(performanceYear = 2017) to return an empty array for years not found.
* https://jira.cms.gov/browse/QPPSF-4331
Reviewers:
@kalvinwang @KyleApfel @bijujoseph @sheldon-b @kyeah @shebryant
=> QPPSF-4331 - Fixed Clinical Cluster Exception for missing 2019 clusters

clinical-clusters/2018/clinical-clusters.json, package-lock.json, package.json, scripts/clinical-clusters/ema-clinical-cluster-builder.js, test/clinical-clusters/clinical-clusters-spec.js
Update/fix Claims and Registry Clinical Clusters as per BA spread sheet
update/fix Claims and Registry Clinical Clusters as per BA spread sheet
After comparison between current clinical cluster data and proposed clinical cluster changes, we have identified the following measures need to be removed from 2018 Registry clinical clusters, 134 and 47 (Palliative Care) , and Claims Clinical Clusters 117, 1 (Diabetic Care), and 226 (General Care)
* https://jira.cms.gov/browse/QPPSF-4346
@sheldon-b @kalvinwang @KyleApfel @bijujoseph @kyeah @shebryant
=> QPPSF-4346 Clinical Cluster Updates

benchmarks/2018.json, package-lock.json, package.json, staging/2018/benchmarks/benchmarks.csv, staging/2018/benchmarks/json/003_benchmarks_cahps.json, staging/2018/benchmarks/json/benchmarks.json
The 2018 historic benchmark file incorrectly contained 5 non-proportion benchmarks. These measures should not have received historic benchmarks because non-proportion measures did not start receiving benchmarks until the 2018 PY (and thus can only be scored against PY benchmarks).
The incorrect file  is replaced with a csv without the non-proportion measures, and a new file for cahps benchmarks is added also. It seems that in a previous PR cahps benchmarks were added directly to the 2018.json file, rather than added as a json file in the staging directory in order to ensure that the benchmarks are added each time the build script is run.
* https://jira.cms.gov/browse/QPPA-3147
=> QPPA-3147: Remove Nonprop Measures from 2018 Benchmarks

benchmarks/2019.json, staging/2019/benchmarks/json/004_benchmarks_acr.json
Measure 458 is a special hybrid cost/quality measure and needs a historical benchmark. Normally, HCQAR generates this benchmark but we need to this year. 
Adding generated benchmark to 2019.json.
* https://jira.cms.gov/browse/QPPA-3210
=> QPPA-3210: Add 2019 historical benchmark for measure 458

measures/2018/measures-schema.yaml, measures/2019/measures-schema.yaml, package-lock.json, package.json
A number of small changes are needed for the measures repo.
The changes that are included in this PR are as follows:
1. firstPerformanceYear - default is changed from 2018 to 2017
2. measureSets - description is updated to "Quality measures can belong to multiple measure sets that represent different specialties."
3. piMeasure object - field "exclusion" is added, with the description, "Identifiers of other PI measures that can be submitted instead of current measure. Cannot submit both current measure and the exclusion measure."
4. typo is fixed in piMeasure substitutes' description - "Identifiers of other PI measures that can be used instead of the current measure."
* [x ] Unit tests added/passing
* …
=> QPPA-3262: Update Measures Repo Schema

package-lock.json, package.json
Both #291 and #293 bumped the version to 1.31.3 but only one of those changes were included when 1.31.3 was published to npm. This resulted in only one of the features being released into PROD when we were expecting both of them to go out.
Bumps the qpp-measures-data repo to 1.31.4 so we can publish the measure 370 change without overriding the version of 1.31.3 that is already deployed to PROD.
The ticket QPPA-3525 is for a feature enabler to add CI to qpp-measures-data. That CI would have helped avoid this scenario and others like it but allowing us to utilize automation for more quality checks and process steps.
=> Bump version to 1.31.4

clinical-clusters/2019/clinical-clusters.json, package.json, scripts/clinical-clusters/ema-clinical-cluster-builder.js, util/clinical-clusters/2019/ClaimsClinical_Cluster.csv, util/clinical-clusters/2019/RegistryClinicalCluster.csv
- Added missing Asthma Care for registry clinical cluster.
- Removed 395, 396, 397 from Pathology claims clinical cluster.
- Updated optional measures 117, 130, 226, 317 for claims clinical clusters.
- Updated optional measures 110, 130, 226 for registry clinical clusters.
- Added missing Asthma Care for registry clinical cluster.
- Removed 395, 396, 397 from Pathology claims clinical cluster.
- Updated optional measures 117, 130, 226, 317 for claims clinical clusters.
- Updated optional measures 110, 130, 226 for registry clinical clusters.
* https://jira.cms.gov/browse/QPPA-5346
@harrisj @lamroger @sheldon-b @kyeah @shebryant @KyleApfel @NateTheGreatt @Jpec07 @bijujoseph
=> QPPSF-5346 - Clinical Cluster Fixes

measures/2019/measures-data.json, package-lock.json, package.json, scripts/measures/2019/get-strata-uuids-from-ecqm-zip.js, util/measures/2019/enriched-measures-data-quality.json, util/measures/2019/generated-ecqm-data.json
CMS22v7 was missing UUID's associated with the 2019 IG here: https://ecqi.healthit.gov/system/files/2019_CMS_QRDA_III_Eligible_Clinicians_and_EP_IG-508.pdf
No ticket, this was found by @StevenSzeliga. CMS22v7 was being skipped and needed to be included.
=> Update CMS22v7 UUIDs

benchmarks/2019.json, package-lock.json, package.json, staging/2019/benchmarks/json/002_benchmarks_aco_cahps.json, staging/2019/benchmarks/json/003_benchmarks_cahps.json
There are 15 entries in the 2019 benchmarks file that show `"performanceYear": 2018`. All entries in this file should be 2019.
JSON files from 2018 CAHPS benchmarks had been uploaded into the 2019 directory because the benchmarks were not changing from 2018 to 2019. However, the `benchmarkYear` and the `performanceYear` were not made current which resulted in comprising 2019 benchmarks with inaccurate data. The files in question where updated to use `benchmarkYear` 2017 and `performanceYear` 2019. 
* https://jira.cms.gov/browse/QPPA-3530
=> QPPA-3530: Remove Y2 Entries From 2019 Benchmarks

README.md
Removed introductory paragraph with the reference to when measures will be added in 2018. Removed a reference to versioning in the introductory paragraph to clarify that the repo is the source of truth.
Updating repo introductory language for 2020. 
Removed introductory paragraph with references to 2018. Removed version reference to clarify that the repo is the source of truth for QPP measures data. 
Review for any additional updates that might be needed to clarify the README
* https://jira.cms.gov/browse/QPPA-3603
=> QPPA-3603 Update README for 2020

benchmarks/2019.json, benchmarks/2019/benchmarks-schema.yaml, package-lock.json, package.json, scripts/benchmarks/format-benchmark-record.js, scripts/benchmarks/parse-benchmarks-data.js, staging/2019/benchmarks/benchmarks.csv, staging/2019/benchmarks/json/benchmarks.json, test/scripts/benchmarks/fixtures/test-benchmarks.csv, test/scripts/benchmarks/format-benchmark-record-spec.js, test/scripts/benchmarks/parse-benchmark-data-spec.js
https://jira.cms.gov/browse/QPPA-3580
https://jira.cms.gov/browse/QPPA-3536
This adds an isToppedOutByProgram field to various benchmarks which is the new 'SevenPointCap' column in the input file.
Additionally, the submission method is now determined using the collection type column. The mapping of new names back to the old is from https://confluence.cms.gov/pages/viewpage.action?spaceKey=QPPARCH&title=Task%3A+Aggregate+Multiple+Submissions+and+Update+Terminology
We are sticking with the older naming schema as the API expects that still.
This also reverts the benchmark changes from #283 as the program has decided to not update these values.
=> QPPA-3580, QPPA-3536 - Update benchmarks for isToppedOutByProgram, revert decile change, and delete benchmarks for measures that no longer exist

benchmarks/2019.json, package-lock.json, package.json, scripts/benchmarks/format-benchmark-record.js, staging/2019/benchmarks/benchmarks.csv, staging/2019/benchmarks/json/benchmarks.json
#310 Mistakenly removed web interface benchmarks from the repo.
The previous WI benchmarks have been added back. Note that we are assuming that the SevenPointCap/isToppedOutByProgram is always false for these values. The average + standard deviation columns are also left blank (and unused in any case).
=> Add back the 2019 cmsWebInterface benchmarks

benchmarks/2019.json, package-lock.json, package.json, staging/2019/benchmarks/benchmarks.csv, staging/2019/benchmarks/json/benchmarks.json
There are some unexpected results from the GET public /benchmarks endpoint when trying to filter by certain ids. 
Previously, a number of benchmarks were deleted from 2019 because they existed for measureIds that are no longer valid for 2019. This issue still exists for a few ids. They are deleted in this PR.
* https://jira.cms.gov/browse/QPPA-3532
=> QPPA-3532: Remove More Benchmarks from 2019 

benchmarks/2019.json, benchmarks/2019/benchmarks-schema.yaml, package-lock.json, package.json, scripts/benchmarks/helpers/merge-benchmark-data-helpers.js, scripts/benchmarks/merge-benchmark-data.js, test/benchmarks/benchmarks-spec.js, test/benchmarks/files/performance-benchmarks.json, test/benchmarks/merge-benchmark-data-spec.js
After the previous PR for this ticket, numerous benchmarks were being duplicated in the published data. This has been corrected, and a validation has been added to ensure that such data should never be written again.
Performance Benchmarks lack the `benchmarkYear` attribute, and so were not being properly flagged as duplicates by the script. This has been corrected, and special handling has been added to ensure that these benchmarks do not overwrite previously-written benchmarks.
In addition, a validation step has been added to the benchmark generation script to ensure that duplicate benchmarks do not make it into the final file.
Numerous code comments were added, the formatting was corrected on some files.
* …
=> [QPPSF-5831] Duplicate Benchmark Fix

.github/release-draft.yml, .github/workflows/draft-release.yml, .github/workflows/pr-feature.yml, .github/workflows/pr-release.yml, .github/workflows/publish.yml
Github workflow for automating release management and notifications.
[Tech Spec](https://confluence.cms.gov/display/QPPARCH/Tech+Spec%3A+Automated+Publication+of+New+Measures+and+updates)
* test runs for both feature and release PRs
- additional version bump check for release PRs
* draft of release page on release merge to master
* on prerelease:
- publish to gpr
- publish to npm
- dispatch of event to dependent projects
- notification of relevant slack channels of publish
The following secrets need to be set by an admin:
* `NPM_TOKEN` for publishing to npm
* `GITHUB_USER_TOKEN` for dispatching of events to other repos
* `SLACK_WEBHOOK` for dispatching notifications to slack
The slack webhook needs to be created by someone with permissions, and the integration will likely require …
=> QPPA-3756 Github Action Workflow

.github/workflows/publish.yml
What is the problem being solved? What is the feature being added?
Adding `CMSgov/beneficiary-reporting-client` to the publish github action so that we can get fancy automatic created PRs when this lib is updated.
=> Updating publish action with CMSgov/beneficiary-reporting-client

benchmarks/2017.json, benchmarks/2017/benchmarks-schema.yaml, benchmarks/2018.json, benchmarks/2018/benchmarks-schema.yaml, staging/2017/benchmarks/json/performance-benchmarks.json, staging/2018/benchmarks/json/performance-benchmarks.json
Adds performance benchmarks to PY17 and PY18 benchmarks
Took performance benchmarks from the submissions api and applied them into the benchmarks stored in the repo. This should bring the repo and DB to parity for PY17 and PY18.
The existing build scripts would not run sucessfully against the existing files in the staging directories. Since this is just adding performance benchmarks in, we used the existing benchmarks file and the new performance benchmarks file the source files and removed all others. The series of steps is outlined below:
1. Retrieved performance benchmarks from prod using script in submission API
* only pulled benchmarks with `status: current`
* saved as `performance-benchmarks.json` in respective staging folders
2. sorted original benchmarks in place for easier …
=> QPPA-4432 update performance benchmarks PY17 PY18

benchmarks/2017.json, benchmarks/2017/benchmarks-schema.yaml, benchmarks/2018.json, benchmarks/2018/benchmarks-schema.yaml, staging/2017/benchmarks/json/performance-benchmarks.json, staging/2018/benchmarks/json/performance-benchmarks.json
Adds performance benchmarks to PY17 and PY18 benchmarks. This PR is a duplicate of #373 which was merged and then reverted.
Took performance benchmarks from the submissions api and applied them into the benchmarks stored in the repo. This should bring the repo and DB to parity for PY17 and PY18.
The existing build scripts would not run sucessfully against the existing files in the staging directories. Since this is just adding performance benchmarks in, we used the existing benchmarks file and the new performance benchmarks file the source files and removed all others. The series of steps is outlined below:
1. Retrieved performance benchmarks from prod using script in submission API
* only pulled benchmarks with `status: current`
* saved as `performance-benchmarks.json` in respective …
=> QPPA-4432 update performance benchmarks 17 18

.github/workflows/publish.yml
Github actions has deprecated `set-env` which the create-pull-request v2 version relied on, resulting in the github actions workflow failing to create a backfill pr once a release branch was merged into master and published.
Upgrading create-pull-request to v3, pinning it to the commit hash of the v3.6.0 release which should address the failing github action. None of the configuration changes between v2 and v3 should affect us.
=> Update create-pull-request to v3.6.0

index.js, measures/2020/measures-data.json, measures/2021/measures-data.json, scripts/measures/2020/import-cahps-measures.js, scripts/measures/2021/import-cahps-measures.js, scripts/measures/build-2020-measures, scripts/measures/build-2021-measures, staging/2021/measures-data-cahps.json, util/measures/2020/cahps-measures.csv, util/measures/2021/cahps-measures.csv
Load PY 2020 and 2021 measures for CAHPS reporting. Measures are unchanged from 2019. ACO scores will not be loaded for these years, but measures are included for the sake of completeness.
* https://jira.cms.gov/browse/QPPA-4987
=> QPPA-4987: 2020-2021 CAHPS Measures

clinical-clusters/2021/clinical-clusters-schema.yaml, clinical-clusters/2021/clinical-clusters.json
Copying 2020 clinical clusters data for 2021 in order to unblock testing of the Quality pipeline in Scoring Engine for Y5.
=> copied clinical cluster data for 2021 testing

benchmarks/2020.json, staging/2020/benchmarks/json/performance-benchmarks.json
Measure ID 478 was part of the PY2020 Final Scoring performance benchmarking delivery. This PR is to make sure the benchmark part of the pool of measures available for view on the Feedback and Measures UI. 
* https://jira.cms.gov/browse/QPPSF-8240
=> QPPSF-8240 - Adding Measures 478 Benchmark PY2020

package.json
Motivation for change
To delivery the latest benchmark for measure 478. Once this release is finalized and delivered, a release v4.5.2 will be generated.
=> Publish Release  v4.5.2

staging/2020/benchmarks/json/wi-benchmarks.json
Non-performance benchmarks should use a benchmark year two years prior to the performance year.
#387 fixed the output of the benchmark script, but not the WI input. If you re-run the script, the output has 2020 for the benchmark year for WI measures. So the input `staging/2021/benchmarks/json/wi-benchmarks.json` file needs to be changed.
* https://jira.cms.gov/browse/QPPA-8206
=> QPPSF-8206: Fix benchmark year for 2020 WI

benchmarks/2021.json, staging/2021/benchmarks/json/wi-benchmarks.json
Y5 benchmark updates for WI
Add the measures required for WI in wi-benchmark.json and add measures to the 2021.json in the benchmark directory.
Reference: https://confluence.cms.gov/display/QPPBSR/Y5+WI+Benchmark+Updates
https://jira.cms.gov/browse/QPPBSR-8035
=> Feature/QPPBSR-8035: PY2021 Y5 WI benchmarks

clinical-clusters/2021/clinical-clusters.json, clinical-clusters/2022/clinical-clusters-schema.yaml, clinical-clusters/2022/clinical-clusters.json, scripts/clinical-clusters/build-clinical-clusters, scripts/clinical-clusters/ema-clinical-cluster-builder.js, util/clinical-clusters/2021/ClaimsClinical_Cluster.csv, util/clinical-clusters/2021/RegistryClinicalCluster.csv
Y5 update for EMA Specialty Sets and Clinical Clusters
Edit: 
- Manually entered the 2022 EMA Clinical Clusters and Specialty sets as a copy of Y5 EMA SS's and CC's.
- This is for ScoringEngines ability to fail gracefully on Y6 EMA. CC: @shadford 
* https://jira.cms.gov/browse/QPPSF-8670
=> QPPSF-8670: Update 2021 EMA Specialty Sets and Clinical Clusters

package.json
Publish Release  Release/4.9.0
- [QPPSF-8670](https://jira.cms.gov/browse/QPPSF-8670): Update 2021 EMA Specialty Sets and Clinical Clusters (#482)
- [QPPA-4742](https://jira.cms.gov/browse/QPPA-4742):  Remove nutritionDietician measureSet from 2021 measure 001 (#480)
* [ X ] [Package version updated](https://github.com/CMSgov/qpp-measures-data/blob/master/CONTRIBUTING.md#versioning-publishing-and-creating-new-releases)
=> Publish Release v4.9.0

benchmarks/2022.json, benchmarks/2022/benchmarks-schema.yaml, package-lock.json, package.json, staging/2022/benchmarks/benchmarks.csv, staging/2022/benchmarks/json/benchmarks.json
Initial 2022 benchmarks
Initial 2022 benchmark file generation from the historical benchmarks
Pulled from Run #2065
```
select measurename, measureid, collectiontype, measuretype, benchmark, standarddeviation, average, decile3, decile4, decile5, decile6, decile7, decile8, decile9, decile10, toppedout, sevenpointcap, highpriority 
from final_scoring_prod.historicalbenchmark_qpp_measures_report_2065 where benchmark = 'Y' order by lpad(measureid, 3, '0'), measuretype, collectiontype
```
=> QPPSF-8478 - Initial 2022 Benchmarks

staging/2022/benchmarks/benchmarks.csv
Adding ACEP50 and ACEP51 back into `benchmarks.csv` with benchmarks removed
Adding ACEP50 and ACEP51 back into `benchmarks.csv` with benchmarks removed
* https://jira.cms.gov/browse/QPPSF-9259
=> QPPSF-9259 - Adding ACEP50 and ACEP51 back into benchmarks.csv with benchmarks removed

benchmarks/2022.json
Measure 117 submissionMethod = claims is suppressed in 2021, thus it cannot be ToppedOutByProgram in 2022.
Updates the PY2022 Benchmark repo for Measure ID 117 submissionMethod = claims:
`isToppedOutByProgram = true --> isToppedOutByProgram = false`
* https://jira.cms.gov/browse/QPPA-6274
=> QPPA-6274: PY22 Update the "isToppedOutByProgram" for Measure 117 (Claims)

benchmarks/2022/benchmarks-schema.yaml, measures/2022/measures-schema.yaml
During the Data Dictionary Audit, some measure and benchmark fields were found to be lacking descriptions in their respective schemas. This PR adds descriptions for those fields.
* https://jira.cms.gov/browse/QPPA-6097
=> QPPA-6097: Update schemas

benchmarks/2021.json, scripts/benchmarks/helpers/merge-benchmark-data-helpers.js, scripts/benchmarks/merge-benchmark-data.js, staging/2021/benchmarks/json/performance-benchmarks.json
Adding in PY21 Performance Benchmarks from the FS Run Id # 2442.
Adding in PY21 Performance Benchmarks from the FS Run Id # 2442. What is odd is when I looked at the `merge-benchmark-data-helpers.js` file the performance benchmark logic had been stripped out, but the git history is vague and seems to be missing. I had to go to an old commit when it was previously added (and fixed) via [this commit.](https://github.com/CMSgov/qpp-measures-data/blob/d2e578dfa3c61ad865da05ada6b52f07151ecec9/scripts/benchmarks/helpers/merge-benchmark-data-helpers.js). Maybe a git rebase gone wrong or otherwise refactoring.
* https://jira.cms.gov/browse/QPPSF-9970
=> QPPSF-9970 - PY21 Performance Benchmarks

measures/2022/measures-data.json, staging/2022/measures-data-quality.json, util/measures/2022/enriched-measures-data-quality.json, util/measures/2022/quality-measures.csv
As part of Y6 requirements, measureId 047 should no longer be required for PCF measurementSets.
* https://jira.cms.gov/browse/QPPA-6448
=> QPPA-6448: remove 047 PCF requirement PY22

scripts/benchmarks/helpers/merge-benchmark-data-helpers.js
Trimming the first decile for proportional measures was added as a quick fix. This should be done in the Final Scoring engine that computes the deciles. The PR for that is [here](https://github.cms.gov/qpp/qppar-final-scoring/pull/1334).
This PR just removes the decile trimming.
* https://jira.cms.gov/browse/QPPSF-10172
=> QPPSF-10172: Remove proportional decile trimming

measures/2022/measures-data.json, measures/2022/measures-schema.yaml, measures/2023/measures-data.json, measures/2023/measures-schema.yaml, scripts/measures/lib/merge-benchmark-metadata.js, test/scripts/measures/lib/merge-benchmark-metadata-spec.js
- Change the benchmarks field in `measures-data.json` to `historic_benchmarks`. The change was made to PY22, but will populate to any year if the build script is rerun for that year.
- Initialize the PY 2023 repo.
These changes are made together in the same PR since the field change in 6517 affects 6772.
* https://jira.cms.gov/browse/QPPA-6517
* https://jira.cms.gov/browse/QPPA-6772
=> QPPA-6517, QPPA-6772: changed benchmarks field to historic_benchmarks, add PY23 Repo

benchmarks/2022/benchmarks-schema.yaml
The latest version of avj is more strict and complains about the lack of a dollar sign in front of the id.
=> QPPA-0000: fix benchmarks schema py22

benchmarks/2022.json, staging/2022/benchmarks/json/wi-benchmarks.json
Update Benchmarks to include 2022 Web Interface
What is the problem being solved? What is the feature being added?
Add the measures required for WI in wi-benchmark.json and add measures to the 2022.json in the benchmark directory.
Reference: https://jira.cms.gov/secure/attachment/1186074/1186074_2022+APM+Performance+Pathway_CMS+Web+Interface+Measure+Benchmarks.pdf
* https://jira.cms.gov/browse/QPPA-8607
=> feature/qppbsr-8607 Update WI 2022 Benchmarks

measures/2023/measures-schema.yaml, scripts/measures/2023/ingest-strata.ts
QPPA-6893 Enforce name and description on strata
Mark as required in yaml. Check that a `name` and `description` exist when ingesting the strata. If not, throw an error.
Also removes `eMeasureUuids` from yaml since they are no longer used
* https://jira.cms.gov/browse/QPPA-6893
=> QPPA-6893 Enforce name and description on strata

measures/2023/measures-data.json
Rmove mips and pcf from the allowedPrograms of 110 and 111 for PY2023, as those measures will only be allowed for their mvps.
* https://jira.cms.gov/browse/QPPA-6932
=> QPPA-6932: remove mips and pcf from 110 and 111 py23

benchmarks/2022.json, staging/2022/benchmarks/benchmarks.csv, staging/2022/benchmarks/json/benchmarks.json
Remove benchmarks for eCQM suppressed measures for PY22
005 submissionMethod = electronicHealthRecord
113 submissionMethod = electronicHealthRecord
134 submissionMethod = electronicHealthRecord
236 submissionMethod = electronicHealthRecord
239 submissionMethod = electronicHealthRecord
281 submissionMethod = electronicHealthRecord
NOTES:
(No action needed for 366 as it's benchmarks are already removed)
In the past there was a `source.csv` that also needed to be updated. This does not exist for 2022 for some reason, but does not affect the rest of the process.
An example of a previous similar PR for 2021: https://github.com/CMSgov/qpp-measures-data/pull/521/files
* https://jira.cms.gov/browse/QPPA-7189
=> QPPA-6789: remove benchmarks for suppressed py22

measures/2022/measures-data.json
Remove historic benchmark for IRIS2 in PY2022.
* https://jira.cms.gov/browse/QPPA-7249
=> QPPA-7249: remove historic bmark iris2 py22

benchmarks/2022.json, measures/2022/measures-data.json, staging/2022/benchmarks/benchmarks.csv, staging/2022/benchmarks/json/benchmarks.json
Remove the historic-benchmarks-removed flag from IROMS measures PY22
* https://jira.cms.gov/browse/QPPA-7285
=> QPPA-7285: Remove the historic-benchmarks-removed flag from IROMS measures PY22

benchmarks/2022.json, staging/2022/benchmarks/json/mock-cost-benchmarks.json
To aid in testing AC and Cost measures adding in benchmark placeholders copied from previous years data and updating the performance year information. This will not be used for any Final Scoring in production and is for test purposes only. These are expected to be replace by the final AC and Cost benchmarks in Summer 2023. 
Placeholder PY22 AC and Cost benchmarks added.
* https://jira.cms.gov/browse/QPPSF-11656
=> QPPSF-11656 - Placeholder PY22 Cost Benchmarks

constants.js, mvp/2023/mvp-enriched.json, mvp/2023/mvp-schema.yaml, mvp/2023/mvp.json
The goal is to add a few key data points in the MVP schema to add more cohesion on the UI.
- administrativeClaimsMeasures -> Singles out specific outcome AC measures.
- allowedVendors -> New field for adding access for specific vendors (empty for now).
- hasCahps -> Does this MVP have CAHPS?
- hasOutcomeAdminClaims -> Is administrativeClaimsMeasures array empty? 
The schema, mvp.json, and the constants file were the main places of manual change. Remainder is system generated.
* https://jira.cms.gov/browse/QPPA-7565
=> QPPA-7565 - PY23 MVP Schema Update

benchmarks/2022.json
Change COST_CCR_1 to COST_CRR_1 in 2022 benchmarks
* https://jira.cms.gov/browse/QPPA-7593
=> QPPA-7593: correct typo in benchmarks 2022

staging/2022/benchmarks/json/mock-cost-benchmarks.json
Fixes the ingestion data for 2022 benchmarks to correct mistyped measureId
=> QPPA-0000: post hotfix cleanup

package-lock.json, package.json, scripts/measures/export-measures, scripts/measures/json-to-csv.ts
correctly labeled QCDRs and Qualities (they were reversed).
Include all columns in CSV (some were missing).
Change `strata` field to boolean for the CSV (array of objects not suited for CSV format).
* https://jira.cms.gov/browse/QPPA-7299
=> QPPA-7299: clean up CSV exporter script

.github/workflows/publish.yml
Comments out other repos (except Sub API) from the publish Action. If other teams want to use this functionality, we can add it back and create a new Personal Access Token that includes writes to their repo in it's scope.
=> QPPA-0000: fix publish action

scripts/measures/2024/update-measures-util.spec.ts, scripts/measures/2024/update-measures-util.ts
---
https://jira.cms.gov/browse/QPPA-7298
---
---
---
---
=> QPPA-7298: adds validation to measures ingestion script

benchmarks/2023/benchmark-exclusion-reasons.json
---
https://jira.cms.gov/browse/QPPSE-670
---
This is a temporary file for testing. Some things will be fixed at a later date. The structure should be correct.
---
---
---
---
---
=> QPPSE-670: Add benchmark exclusion reasons JSON

clinical-clusters/2023/clinical-clusters-schema.yaml, index.js, measures/2017/measures-schema.yaml, measures/2018/measures-schema.yaml, measures/2019/measures-schema.yaml, measures/2020/measures-schema.yaml, measures/2021/measures-schema.yaml, measures/2022/measures-schema.yaml, measures/2023/measures-schema.yaml, measures/2024/measures-schema.yaml, package-lock.json, package.json, scripts/validate-data.js, test/measures/measures-schema-spec.js
---
https://jira.cms.gov/browse/QPPA-8070
---
---
---
---
=> QPPA-8070: Implement new yaml parser

measures/2024/measures-data.json, mvp/2024/mvp-enriched.json, updates/measures/2024/Quality_QCDR_PY24_CR_20231211.csv, updates/measures/2024/changes.meta.json, util/measures/2024/qcdr-strata.csv
---
https://jira.cms.gov/browse/QPPA-8300
https://jira.cms.gov/browse/QPPA-8464
---
New measure 'AAD19' added.
New measure 'AAN35' added.
New measure 'AAN36' added.
New measure 'AAO37' added.
New measure 'AAO38' added.
New measure 'AAO39' added.
New measure 'ABFM13' added.
New measure 'ACEP64' added.
New measure 'ACEP65' added.
New measure 'ACEP66' added.
New measure 'AJRR12' added.
New measure 'AQUA35' added.
New measure 'AQUA36' added.
New measure 'CAP40' added.
New measure 'CAP41' added.
New measure 'CAP42' added.
New measure 'ECPR59' added.
New measure 'GIQIC26' added.
New measure 'HCPR25' added.
New measure 'HCPR26' added.
New measure 'HCPR27' added.
New measure 'IRIS61' added. …
=> QPPA-8300: Update Quality measures for PY24

CODEOWNERS, measures/2023/measures-data.json, mvp/2023/mvp-enriched.json, scripts/measures/2023/get-strata-uuids-from-ecqm-zip.js, util/measures/2023/generated-ecqm-data.json, util/measures/2023/manually-created-missing-measures.json
---
https://jira.cms.gov/browse/QPPSE-1513
https://github.com/CMSgov/qpp-conversion-tool/issues/1400
---
Added strata for measure `CMS347v6` and missing field `numeratorExclusionUuid` for `CMS156v11` and `CMS249v5`
---
---
---
=> QPPSE-1513: Updated measures data based on the conversion tool git issue #1400

CONTRIBUTING.md, constants.js
https://jira.cms.gov/browse/QPPA-8644
---
---
---
---
=> QPPA-8644: adds 2024 to the valid performance years array

.github/workflows/draft-release.yml
---
The Draft-release Action is throwing warnings that a package uses node v12 which will soon be removed. This PR updates the packages to use their latest versions
---
---
---
---
---
=> QPPA-0000: fix draft-release action

measures/2024/measures-data.json, mvp/2024/mvp-enriched.json
https://jira.cms.gov/browse/QPPA-8708
---
---
---
---
---
---
=> QPPA-8708: Remove PI_EP_2_EX_3 from PY2024

index.spec.ts, index.ts
https://jira.cms.gov/browse/QPPA-9642
---
There was a bug in the previous PR (contained in the same release as this) where the enum was being cast to an object. This fixes that issue.
---
---
---
- `notes:*`
- `version:*`
---
---
=> QPPA-9642: fix enum typing

measures/2024/measures-data.json, mvp/2024/mvp-enriched.json, scripts/measures/2024/update-measures.ts, scripts/measures/2025/update-measures.ts, scripts/measures/lib/measures-lib.spec.ts, scripts/measures/lib/measures-lib.ts, updates/measures/2024/Quality_2024_Suppression_488_389_CR_03182025.csv, updates/measures/2024/changes.meta.json
https://jira.cms.gov/browse/QPPA-9692
---
PY24 - Suppress measure 488
collectionType = eCQM
isClinicalGuidelineChanged = true
clinicalGuidelineChanged = electronicHealthRecord
PY24 - Suppress measure 389
collectionType = MIPS CQM
isClinicalGuidelineChanged = true
clinicalGuidelineChanged = registry
---
---
---
=> QPPA-9692: supress measure 488 & 389

benchmarks/2024/cost-national-averages.json
https://jira.cms.gov/browse/QPPC-7309
---
Adding in the PY 2024 `cost-national-averages.json` file.
---
---
---
- `notes:*`
- `version:*`
---
---
=> QPPC-7309: Adding Cost National Averages Data for PY 2024
